Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (1, 'Music', 'Piano Course', 15, 106, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 59, 0, '/assets/images/paige-cody-7kck7rSl_Bo-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (2, 'Music', 'Guitar Course', 16, 10, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 99, 1, '/assets/images/jacek-dylag-hUHzaiAHuUc-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (3, 'Math', 'Math Matrix Course', 3, 6, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 29, 5, '/assets/images/thisisengineering-raeng-GzDrm7SYQ0g-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (4, 'Language', 'English Course', 8, 1060, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 75, 3, '/assets/images/ivan-shilov-ucUB9wxkPgY-unsplash.jpg');

Insert into tags (tag_name, description, course_id) values ('Music', 'Some Not long not short description about tag', 1);
Insert into tags (tag_name, description, course_id) values ('Music', 'Some Not long not short description about tag', 2);
Insert into tags (tag_name, description, course_id) values ('Math', 'Some Not long not short description about tag', 3);
Insert into tags (tag_name, description, course_id) values ('Language', 'Some Not long not short description about tag', 4);
