Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (1, 'Music', 'Piano Course', 15, 106, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 59, 0, '/assets/images/paige-cody-7kck7rSl_Bo-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (2, 'Music', 'Guitar Course', 16, 10, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 99, 1, '/assets/images/jacek-dylag-hUHzaiAHuUc-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (3, 'Math', 'Math Matrix Course', 3, 6, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 29, 5, '/assets/images/thisisengineering-raeng-GzDrm7SYQ0g-unsplash.jpg');
Insert into courses (id, tag, title, duration, students, short_description, long_description, price, rating, picture_path) values (4, 'Language', 'English Course', 8, 1060, 'Proactively parallel task vertical products for collaborative ideas. Monotonectally visualize functional functionalities vis-a-vis efficient products. Globally matrix bleeding-edge e-business with professional.', 'Long Desc', 75, 3, '/assets/images/ivan-shilov-ucUB9wxkPgY-unsplash.jpg');

Insert into tags (tag_name, description, course_id) values ('Music', 'Some Not long not short description about tag', 1);
Insert into tags (tag_name, description, course_id) values ('Music', 'Some Not long not short description about tag', 2);
Insert into tags (tag_name, description, course_id) values ('Math', 'Some Not long not short description about tag', 3);
Insert into tags (tag_name, description, course_id) values ('Language', 'Some Not long not short description about tag', 4);

Insert into reviews (user_name, feed_back, course_id) values ('Anonymous User', 'This is a wonderful starting course. You will find everything in this course to get you properly starting out on guitar. I highly recommend this course for anyone who has yet to take lessons.', 2);
Insert into reviews (user_name, feed_back, course_id) values ('Anonymous User', 'You are very familiar with music.You explain the subject very well.Thank you teacher.', 2);
Insert into reviews (user_name, feed_back, course_id) values ('Anonymous User', 'Amazing course. Don''t think about that u ar in the right place ;)', 2);
